// Seed третьей партии городов (10 зарубежных направлений).
// Запуск: node scripts/seed-batch-3.mjs
import { createClient } from "@supabase/supabase-js";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const SB_URL = fs.readFileSync(path.join(os.homedir(), ".relocost/supabase_url"), "utf8").trim();
const SB_KEY = fs.readFileSync(path.join(os.homedir(), ".relocost/supabase_service_role_key"), "utf8").trim();
const sb = createClient(SB_URL, SB_KEY, { auth: { persistSession: false } });

const CITIES = [
  {
    name_ru: "София", name_en: "Sofia", slug: "sofia",
    country_ru: "Болгария", country_en: "Bulgaria", country_slug: "bulgaria", flag_emoji: "🇧🇬",
    population: "1.2 млн", climate: "+12°C ср.", language: "Болгарский, русский, английский", currency: "Лев, BGN",
    flight_from_moscow: "3.5 часа", is_foreign: true, difficulty_score: 2, is_popular: true,
    seo_title: "Стоимость жизни в Софии в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Софии? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Самая доступная столица ЕС: евро-перспектива, низкие цены и понятная бюрократия для россиян. София популярна для релокации через бизнес-ВНЖ и обучение детей в международных школах.",
    lat: 42.6977, lng: 23.3219,
  },
  {
    name_ru: "Варна", name_en: "Varna", slug: "varna",
    country_ru: "Болгария", country_en: "Bulgaria", country_slug: "bulgaria", flag_emoji: "🇧🇬",
    population: "335 тыс", climate: "+13°C ср.", language: "Болгарский, русский", currency: "Лев, BGN",
    flight_from_moscow: "3 часа", is_foreign: true, difficulty_score: 2, is_popular: true,
    seo_title: "Стоимость жизни в Варне в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Варне? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Морская столица Болгарии: пляжи, мягкий климат, доступная аренда и большое русскоязычное комьюнити. Реальный путь к ВНЖ через покупку недвижимости и спокойная жизнь у моря в ЕС-перспективе.",
    lat: 43.2141, lng: 27.9147,
  },
  {
    name_ru: "Афины", name_en: "Athens", slug: "athens",
    country_ru: "Греция", country_en: "Greece", country_slug: "greece", flag_emoji: "🇬🇷",
    population: "3.1 млн", climate: "+18°C ср.", language: "Греческий, английский", currency: "Евро, EUR",
    flight_from_moscow: "4 часа", is_foreign: true, difficulty_score: 3, is_popular: true,
    seo_title: "Стоимость жизни в Афинах в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Афинах? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Шенгенский город с Golden Visa от 250 000 евро: путь к гражданству ЕС, теплая зима и развитая русскоязычная инфраструктура. Город сочетает античное наследие и современную IT-сцену.",
    lat: 37.9838, lng: 23.7275,
  },
  {
    name_ru: "Валенсия", name_en: "Valencia", slug: "valencia",
    country_ru: "Испания", country_en: "Spain", country_slug: "spain", flag_emoji: "🇪🇸",
    population: "790 тыс", climate: "+18°C ср.", language: "Испанский, валенсийский, английский", currency: "Евро, EUR",
    flight_from_moscow: "5 часов", is_foreign: true, difficulty_score: 3, is_popular: true,
    seo_title: "Стоимость жизни в Валенсии в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Валенсии? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Средиземноморская альтернатива Барселоне: дешевле на 30%, тот же климат и более простой ритм. Популярна для релокации фрилансеров через цифровую кочевую визу и семей с детьми.",
    lat: 39.4699, lng: -0.3763,
  },
  {
    name_ru: "Никосия", name_en: "Nicosia", slug: "nicosia",
    country_ru: "Кипр", country_en: "Cyprus", country_slug: "cyprus", flag_emoji: "🇨🇾",
    population: "330 тыс", climate: "+20°C ср.", language: "Греческий, английский, русский", currency: "Евро, EUR",
    flight_from_moscow: "4 часа", is_foreign: true, difficulty_score: 2, is_popular: true,
    seo_title: "Стоимость жизни в Никосии в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Никосии? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Деловая столица Кипра с круглогодичной IT-индустрией и доступными ценами по сравнению с Лимассолом. Английский язык повсюду, прозрачная налоговая система и упрощенная процедура ВНЖ для россиян.",
    lat: 35.1856, lng: 33.3823,
  },
  {
    name_ru: "Пафос", name_en: "Paphos", slug: "paphos",
    country_ru: "Кипр", country_en: "Cyprus", country_slug: "cyprus", flag_emoji: "🇨🇾",
    population: "36 тыс", climate: "+20°C ср.", language: "Греческий, английский, русский", currency: "Евро, EUR",
    flight_from_moscow: "4 часа", is_foreign: true, difficulty_score: 2, is_popular: true,
    seo_title: "Стоимость жизни в Пафосе в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Пафосе? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Самый теплый курорт Кипра с мягкой зимой и развитой инфраструктурой для русскоязычных. Реальный путь к ПМЖ через покупку недвижимости от 300 000 евро, школы и медицина высокого уровня.",
    lat: 34.7768, lng: 32.4245,
  },
  {
    name_ru: "Дубровник", name_en: "Dubrovnik", slug: "dubrovnik",
    country_ru: "Хорватия", country_en: "Croatia", country_slug: "croatia", flag_emoji: "🇭🇷",
    population: "42 тыс", climate: "+17°C ср.", language: "Хорватский, английский", currency: "Евро, EUR",
    flight_from_moscow: "5 часов", is_foreign: true, difficulty_score: 3, is_popular: true,
    seo_title: "Стоимость жизни в Дубровнике в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Дубровнике? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Шенгенский город на Адриатике с цифровой кочевой визой на 1 год и доступом ко всему ЕС. Сочетает средневековый туризм и спокойную работу удаленно у моря.",
    lat: 42.6507, lng: 18.0944,
  },
  {
    name_ru: "Куала-Лумпур", name_en: "Kuala Lumpur", slug: "kuala-lumpur",
    country_ru: "Малайзия", country_en: "Malaysia", country_slug: "malaysia", flag_emoji: "🇲🇾",
    population: "1.8 млн", climate: "+27°C ср.", language: "Малайский, английский, китайский", currency: "Ринггит, MYR",
    flight_from_moscow: "11 часов", is_foreign: true, difficulty_score: 2, is_popular: true,
    seo_title: "Стоимость жизни в Куала-Лумпуре в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Куала-Лумпуре? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Тропический мегаполис с программой MM2H — долгосрочной визой для удаленщиков. Английский повсюду, ультрамодерн рядом с азиатскими рынками, лучшие частные школы и медицина региона.",
    lat: 3.1390, lng: 101.6869,
  },
  {
    name_ru: "Дананг", name_en: "Da Nang", slug: "da-nang",
    country_ru: "Вьетнам", country_en: "Vietnam", country_slug: "vietnam", flag_emoji: "🇻🇳",
    population: "1.1 млн", climate: "+26°C ср.", language: "Вьетнамский, английский", currency: "Донг, VND",
    flight_from_moscow: "12 часов", is_foreign: true, difficulty_score: 2, is_popular: true,
    seo_title: "Стоимость жизни в Дананге в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Дананге? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Растущая столица диджитал-номадов Вьетнама: длинный пляж, теплое море круглый год, очень низкие цены и удобная виза. Город сочетает курортный темп и развитую IT-инфраструктуру.",
    lat: 16.0544, lng: 108.2022,
  },
  {
    name_ru: "Нячанг", name_en: "Nha Trang", slug: "nha-trang",
    country_ru: "Вьетнам", country_en: "Vietnam", country_slug: "vietnam", flag_emoji: "🇻🇳",
    population: "535 тыс", climate: "+27°C ср.", language: "Вьетнамский, английский, русский", currency: "Донг, VND",
    flight_from_moscow: "10 часов", is_foreign: true, difficulty_score: 2, is_popular: true,
    seo_title: "Стоимость жизни в Нячанге в 2026 году — калькулятор бюджета | Relocost",
    seo_description: "Сколько стоит жить в Нячанге? Аренда, еда, транспорт — считаем реальный бюджет. Калькулятор, цены, отзывы переехавших.",
    intro_text: "Курорт с самой большой русскоязычной диаспорой в Юго-Восточной Азии: меню на русском, прямые рейсы из РФ, низкие цены и теплый океан круглый год. Подходит для зимовки и долгой удаленной работы.",
    lat: 12.2388, lng: 109.1967,
  },
];

const PRICES = {
  sofia: [
    ["rent","Комната",18000,30000,false],
    ["rent","1-комн. квартира в центре",45000,70000,false],
    ["rent","1-комн. квартира на окраине",28000,45000,false],
    ["rent","2-комн. квартира в центре",65000,100000,false],
    ["food","Обед в кафе",700,1300,false],
    ["food","Ужин на двоих в ресторане",3500,6500,false],
    ["food","Капучино",200,350,false],
    ["food","Продукты на месяц на 1 человека",20000,30000,false],
    ["transport","Месячный проездной",2300,3000,false],
    ["transport","Такси 3 км",400,700,false],
    ["transport","Бензин (1 л)",130,160,false],
    ["utilities","ЖКХ за 1-комн. квартиру",5500,9000,false],
    ["utilities","Домашний интернет",1400,2300,false],
    ["utilities","Мобильная связь (месяц)",800,1500,false],
    ["cafe","Стейк в ресторане среднего класса",3000,5000,true],
    ["cafe","Коктейль в баре",700,1200,true],
    ["health","Визит к частному врачу",3500,5500,true],
    ["health","Абонемент в фитнес-клуб (мес)",3500,6000,true],
    ["entertainment","Билет в кино",500,800,true],
    ["entertainment","Бокал вина или коктейль в баре",500,900,true],
  ],
  varna: [
    ["rent","Комната",15000,25000,false],
    ["rent","1-комн. квартира в центре",35000,55000,false],
    ["rent","1-комн. квартира на окраине",22000,35000,false],
    ["rent","2-комн. квартира в центре",55000,85000,false],
    ["food","Обед в кафе",600,1100,false],
    ["food","Ужин на двоих в ресторане",3000,5500,false],
    ["food","Капучино",180,300,false],
    ["food","Продукты на месяц на 1 человека",18000,28000,false],
    ["transport","Месячный проездной",2000,2800,false],
    ["transport","Такси 3 км",350,650,false],
    ["transport","Бензин (1 л)",130,160,false],
    ["utilities","ЖКХ за 1-комн. квартиру",4500,7500,false],
    ["utilities","Домашний интернет",1300,2200,false],
    ["utilities","Мобильная связь (месяц)",700,1400,false],
    ["cafe","Стейк в ресторане среднего класса",2500,4500,true],
    ["cafe","Коктейль в баре",600,1100,true],
    ["health","Визит к частному врачу",3000,5000,true],
    ["health","Абонемент в фитнес-клуб (мес)",3000,5500,true],
    ["entertainment","Билет в кино",500,800,true],
    ["entertainment","Бокал вина или коктейль в баре",450,800,true],
  ],
  athens: [
    ["rent","Комната",22000,36000,false],
    ["rent","1-комн. квартира в центре",55000,90000,false],
    ["rent","1-комн. квартира на окраине",38000,60000,false],
    ["rent","2-комн. квартира в центре",80000,130000,false],
    ["food","Обед в кафе",800,1500,false],
    ["food","Ужин на двоих в ресторане",4500,7500,false],
    ["food","Капучино",250,400,false],
    ["food","Продукты на месяц на 1 человека",25000,35000,false],
    ["transport","Месячный проездной",2900,3500,false],
    ["transport","Такси 3 км",550,950,false],
    ["transport","Бензин (1 л)",170,200,false],
    ["utilities","ЖКХ за 1-комн. квартиру",7000,12000,false],
    ["utilities","Домашний интернет",1700,2700,false],
    ["utilities","Мобильная связь (месяц)",1000,1800,false],
    ["cafe","Стейк в ресторане среднего класса",3500,5500,true],
    ["cafe","Коктейль в баре",800,1400,true],
    ["health","Визит к частному врачу",4500,7500,true],
    ["health","Абонемент в фитнес-клуб (мес)",4500,7500,true],
    ["entertainment","Билет в кино",700,1000,true],
    ["entertainment","Бокал вина или коктейль в баре",700,1200,true],
  ],
  valencia: [
    ["rent","Комната",30000,45000,false],
    ["rent","1-комн. квартира в центре",75000,110000,false],
    ["rent","1-комн. квартира на окраине",50000,75000,false],
    ["rent","2-комн. квартира в центре",100000,150000,false],
    ["food","Обед в кафе",1000,1800,false],
    ["food","Ужин на двоих в ресторане",5000,8500,false],
    ["food","Капучино",200,350,false],
    ["food","Продукты на месяц на 1 человека",28000,40000,false],
    ["transport","Месячный проездной",4500,5500,false],
    ["transport","Такси 3 км",550,900,false],
    ["transport","Бензин (1 л)",150,180,false],
    ["utilities","ЖКХ за 1-комн. квартиру",8000,13000,false],
    ["utilities","Домашний интернет",2000,3000,false],
    ["utilities","Мобильная связь (месяц)",1200,2000,false],
    ["cafe","Стейк в ресторане среднего класса",3800,6000,true],
    ["cafe","Коктейль в баре",800,1400,true],
    ["health","Визит к частному врачу",5500,9000,true],
    ["health","Абонемент в фитнес-клуб (мес)",4500,7500,true],
    ["entertainment","Билет в кино",700,1000,true],
    ["entertainment","Бокал вина или коктейль в баре",600,1100,true],
  ],
  nicosia: [
    ["rent","Комната",25000,40000,false],
    ["rent","1-комн. квартира в центре",60000,95000,false],
    ["rent","1-комн. квартира на окраине",40000,65000,false],
    ["rent","2-комн. квартира в центре",85000,140000,false],
    ["food","Обед в кафе",800,1400,false],
    ["food","Ужин на двоих в ресторане",4500,7500,false],
    ["food","Капучино",250,400,false],
    ["food","Продукты на месяц на 1 человека",24000,36000,false],
    ["transport","Месячный проездной",3500,4500,false],
    ["transport","Такси 3 км",600,1000,false],
    ["transport","Бензин (1 л)",140,170,false],
    ["utilities","ЖКХ за 1-комн. квартиру",6500,11000,false],
    ["utilities","Домашний интернет",1800,2800,false],
    ["utilities","Мобильная связь (месяц)",1000,1800,false],
    ["cafe","Стейк в ресторане среднего класса",3500,5500,true],
    ["cafe","Коктейль в баре",800,1400,true],
    ["health","Визит к частному врачу",5000,8000,true],
    ["health","Абонемент в фитнес-клуб (мес)",4500,7500,true],
    ["entertainment","Билет в кино",700,1000,true],
    ["entertainment","Бокал вина или коктейль в баре",700,1200,true],
  ],
  paphos: [
    ["rent","Комната",27000,42000,false],
    ["rent","1-комн. квартира в центре",65000,100000,false],
    ["rent","1-комн. квартира на окраине",42000,65000,false],
    ["rent","2-комн. квартира в центре",90000,150000,false],
    ["food","Обед в кафе",900,1500,false],
    ["food","Ужин на двоих в ресторане",4800,8000,false],
    ["food","Капучино",250,400,false],
    ["food","Продукты на месяц на 1 человека",24000,36000,false],
    ["transport","Месячный проездной",3500,4500,false],
    ["transport","Такси 3 км",650,1100,false],
    ["transport","Бензин (1 л)",140,170,false],
    ["utilities","ЖКХ за 1-комн. квартиру",7000,11500,false],
    ["utilities","Домашний интернет",1900,2900,false],
    ["utilities","Мобильная связь (месяц)",1000,1800,false],
    ["cafe","Стейк в ресторане среднего класса",3700,5800,true],
    ["cafe","Коктейль в баре",800,1400,true],
    ["health","Визит к частному врачу",5500,8500,true],
    ["health","Абонемент в фитнес-клуб (мес)",4800,8000,true],
    ["entertainment","Билет в кино",700,1000,true],
    ["entertainment","Бокал вина или коктейль в баре",700,1200,true],
  ],
  dubrovnik: [
    ["rent","Комната",28000,45000,false],
    ["rent","1-комн. квартира в центре",65000,110000,false],
    ["rent","1-комн. квартира на окраине",45000,70000,false],
    ["rent","2-комн. квартира в центре",90000,150000,false],
    ["food","Обед в кафе",900,1700,false],
    ["food","Ужин на двоих в ресторане",5500,9000,false],
    ["food","Капучино",250,400,false],
    ["food","Продукты на месяц на 1 человека",26000,38000,false],
    ["transport","Месячный проездной",2800,3500,false],
    ["transport","Такси 3 км",700,1200,false],
    ["transport","Бензин (1 л)",140,170,false],
    ["utilities","ЖКХ за 1-комн. квартиру",7000,11000,false],
    ["utilities","Домашний интернет",1900,2900,false],
    ["utilities","Мобильная связь (месяц)",1100,1900,false],
    ["cafe","Стейк в ресторане среднего класса",4000,6500,true],
    ["cafe","Коктейль в баре",900,1500,true],
    ["health","Визит к частному врачу",4500,7000,true],
    ["health","Абонемент в фитнес-клуб (мес)",4500,7500,true],
    ["entertainment","Билет в кино",700,1000,true],
    ["entertainment","Бокал вина или коктейль в баре",700,1300,true],
  ],
  "kuala-lumpur": [
    ["rent","Комната",18000,30000,false],
    ["rent","1-комн. квартира в центре",45000,80000,false],
    ["rent","1-комн. квартира на окраине",28000,48000,false],
    ["rent","2-комн. квартира в центре",70000,120000,false],
    ["food","Обед в кафе",400,900,false],
    ["food","Ужин на двоих в ресторане",2500,5000,false],
    ["food","Капучино",250,400,false],
    ["food","Продукты на месяц на 1 человека",18000,28000,false],
    ["transport","Месячный проездной",2000,2800,false],
    ["transport","Такси 3 км",350,700,false],
    ["transport","Бензин (1 л)",110,140,false],
    ["utilities","ЖКХ за 1-комн. квартиру",4500,8000,false],
    ["utilities","Домашний интернет",1300,2300,false],
    ["utilities","Мобильная связь (месяц)",700,1400,false],
    ["cafe","Стейк в ресторане среднего класса",2500,4500,true],
    ["cafe","Коктейль в баре",700,1400,true],
    ["health","Визит к частному врачу",3000,5500,true],
    ["health","Абонемент в фитнес-клуб (мес)",3500,6500,true],
    ["entertainment","Билет в кино",500,800,true],
    ["entertainment","Бокал вина или коктейль в баре",700,1300,true],
  ],
  "da-nang": [
    ["rent","Комната",10000,17000,false],
    ["rent","1-комн. квартира в центре",25000,45000,false],
    ["rent","1-комн. квартира на окраине",15000,28000,false],
    ["rent","2-комн. квартира в центре",40000,65000,false],
    ["food","Обед в кафе",300,700,false],
    ["food","Ужин на двоих в ресторане",1800,3800,false],
    ["food","Капучино",200,350,false],
    ["food","Продукты на месяц на 1 человека",14000,22000,false],
    ["transport","Месячный проездной",1500,2300,false],
    ["transport","Такси 3 км",250,550,false],
    ["transport","Бензин (1 л)",90,115,false],
    ["utilities","ЖКХ за 1-комн. квартиру",3500,6500,false],
    ["utilities","Домашний интернет",1000,1800,false],
    ["utilities","Мобильная связь (месяц)",500,1100,false],
    ["cafe","Стейк в ресторане среднего класса",1800,3500,true],
    ["cafe","Коктейль в баре",500,1000,true],
    ["health","Визит к частному врачу",2500,5000,true],
    ["health","Абонемент в фитнес-клуб (мес)",2500,5000,true],
    ["entertainment","Билет в кино",400,700,true],
    ["entertainment","Бокал вина или коктейль в баре",500,900,true],
  ],
  "nha-trang": [
    ["rent","Комната",11000,18000,false],
    ["rent","1-комн. квартира в центре",28000,48000,false],
    ["rent","1-комн. квартира на окраине",17000,30000,false],
    ["rent","2-комн. квартира в центре",42000,70000,false],
    ["food","Обед в кафе",300,700,false],
    ["food","Ужин на двоих в ресторане",1800,4000,false],
    ["food","Капучино",200,350,false],
    ["food","Продукты на месяц на 1 человека",14000,22000,false],
    ["transport","Месячный проездной",1500,2300,false],
    ["transport","Такси 3 км",250,550,false],
    ["transport","Бензин (1 л)",90,115,false],
    ["utilities","ЖКХ за 1-комн. квартиру",3500,6500,false],
    ["utilities","Домашний интернет",1000,1800,false],
    ["utilities","Мобильная связь (месяц)",500,1100,false],
    ["cafe","Стейк в ресторане среднего класса",1800,3500,true],
    ["cafe","Коктейль в баре",500,1000,true],
    ["health","Визит к частному врачу",2500,5000,true],
    ["health","Абонемент в фитнес-клуб (мес)",2500,5000,true],
    ["entertainment","Билет в кино",400,700,true],
    ["entertainment","Бокал вина или коктейль в баре",500,900,true],
  ],
};

for (const c of CITIES) {
  const { data: existing } = await sb.from("cities").select("id").eq("slug", c.slug).maybeSingle();
  if (existing) {
    console.log(`skip (exists): ${c.slug}`);
    continue;
  }
  const row = {
    name_ru: c.name_ru, name_en: c.name_en, slug: c.slug,
    country_ru: c.country_ru, country_en: c.country_en, country_slug: c.country_slug,
    flag_emoji: c.flag_emoji, population: c.population, climate: c.climate,
    language: c.language, currency: c.currency, flight_from_moscow: c.flight_from_moscow,
    is_foreign: c.is_foreign, difficulty_score: c.difficulty_score, is_popular: c.is_popular,
    seo_title: c.seo_title, seo_description: c.seo_description, intro_text: c.intro_text,
    lat: c.lat, lng: c.lng,
  };
  const { data: inserted, error } = await sb.from("cities").insert(row).select("id").single();
  if (error) throw new Error(`insert ${c.slug}: ${error.message}`);
  const cityId = inserted.id;

  const prices = (PRICES[c.slug] || []).map(([cat, item, min, max, prem]) => ({
    city_id: cityId, category: cat, item_name_ru: item,
    price_min: min, price_max: max, is_premium: prem,
  }));
  if (prices.length) {
    const { error: pErr } = await sb.from("prices").insert(prices);
    if (pErr) throw new Error(`prices ${c.slug}: ${pErr.message}`);
  }
  console.log(`+ ${c.slug}: city + ${prices.length} prices`);
}
console.log("done.");
